services:
  hapi-fhir-jpaserver-start:
    build: .
    restart: on-failure
    depends_on:
      - hapi-fhir-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hapi-fhir-postgres:5432/hapi
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      LOCATION_CITY: ${LOCATION_CITY:-C91}
    volumes:
      - ./custom:/app/custom
      - ./configs:/app/configs
    ports:
      - "8091:8091"
  hapi-fhir-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    tmpfs:
      - /var/lib/postgresql/data
